openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/v1/users/{id}:
    get:
      tags:
      - user-rest-controller
      operationId: getUser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserModelDTO"
  /api/v1/notes/{id}:
    get:
      tags:
      - ai-note-rest-controller
      operationId: getNote
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AINoteDTO"
components:
  schemas:
    UserModelDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
        role:
          type: string
        status:
          type: string
    AINoteDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        overview:
          type: string
        summary:
          type: string
        jsonQuestions:
          type: string
        visibility:
          type: boolean
        userId:
          type: integer
          format: int64
